sudo: false
branches: cxx
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost1.55-dev
      install:
        - export CC=gcc-6
        - export CXX=g++-6
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libboost1.55-dev
      install:
        - export CC=clang-5.0
        - export CXX=clang++-5.0

script:
  - make