sudo: false
branches: cxx
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libboost-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      install:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libboost-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      install:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

script:
  - make